
# ##Universal Function

ufanc---> stand for Universal function and they are actually numpy function that operates on the ndarray object
ufanc also takes additional arguments like, where, dtype and out.
Vectorization - Converting the iterative statement into a vector based statement.

In [32]:
# Example without universal Function 

In [35]:
x=[23,56,78,99]

In [36]:
y=[45,78,334,0]

In [37]:
z=[]
for i,j in zip(x,y):
    z.append(i+j)
print(z)

[68, 134, 412, 99]


In [17]:

import numpy as np

In [28]:
arr1=np.array([4,67,99,67])
type(arr1)
arr1


array([ 4, 67, 99, 67])

In [29]:
arr2=np.array([68,99,1,0])
type(arr2)
arr2

array([68, 99,  1,  0])

In [30]:
np.add(arr1,arr2)

array([ 72, 166, 100,  67])

In [38]:
np.subtract(arr1,arr2)

array([-64, -32,  98,  67])

In [40]:
 np.divide(arr1,arr2)

C:\Users\iamka\AppData\Local\Temp\ipykernel_8820\3612482896.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(arr1,arr2)


array([5.88235294e-02, 6.76767677e-01, 9.90000000e+01,            inf])

In [47]:

c=np.array([[23,45,-78],[34,-67,99]])
c

array([[ 23,  45, -78],
       [ 34, -67,  99]])

In [49]:
np.abs(c)

In [48]:
np.absolute(c)

array([[23, 45, 78],
       [34, 67, 99]])

In [51]:
np.exp(c)

array([[9.74480345e+09, 3.49342711e+19, 1.33361482e-34],
       [5.83461743e+14, 7.98490425e-30, 9.88903032e+42]])

In [52]:
np.sin(c)

array([[-0.8462204 ,  0.85090352, -0.51397846],
       [ 0.52908269,  0.85551998, -0.99920683]])

In [53]:
np.cos(c)

array([[-0.53283302,  0.52532199, -0.85780309],
       [-0.84857027, -0.5177698 ,  0.03982088]])

In [54]:
np.log(arr1)

array([1.38629436, 4.20469262, 4.59511985, 4.20469262])

In [61]:
np.power(arr1,3)

array([    64, 300763, 970299, 300763], dtype=int32)

In [59]:
np.square(arr1)

array([  16, 4489, 9801, 4489], dtype=int32)

In [62]:
np.sqrt(arr2)

array([8.24621125, 9.94987437, 1.        , 0.        ])

In [63]:
np.tan(c)

array([[  1.58815308,   1.61977519,   0.59918   ],
       [ -0.62349896,  -1.65231726, -25.09253498]])

In [65]:
np.arcsin(arr1)

C:\Users\iamka\AppData\Local\Temp\ipykernel_8820\893717680.py:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(arr1)


array([nan, nan, nan, nan])

In [68]:
np.arccos(c)

C:\Users\iamka\AppData\Local\Temp\ipykernel_8820\3919857117.py:1: RuntimeWarning: invalid value encountered in arccos
  np.arccos(c)


array([[nan, nan, nan],
       [nan, nan, nan]])

In [69]:
np.arctan(c)

array([[ 1.52734543,  1.54857776, -1.55797652],
       [ 1.54139304, -1.55587206,  1.56069566]])

In [70]:
np.vstack(arr1)

array([[ 4],
       [67],
       [99],
       [67]])

In [71]:
np.dstack(arr2)

array([[[68, 99,  1,  0]]])

In [4]:
a=np.arange(27).reshape(3,3,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [11]:
b=np.array([[[4,8,9],[1,2,3],[4,57,7]],[[78,67,0],[67,8,1],[7,8,9]],[[6,55,88],[1,5,7],[5,77,8]]])
b

array([[[ 4,  8,  9],
        [ 1,  2,  3],
        [ 4, 57,  7]],

       [[78, 67,  0],
        [67,  8,  1],
        [ 7,  8,  9]],

       [[ 6, 55, 88],
        [ 1,  5,  7],
        [ 5, 77,  8]]])

In [12]:
np.add(a,b)

array([[[  4,   9,  11],
        [  4,   6,   8],
        [ 10,  64,  15]],

       [[ 87,  77,  11],
        [ 79,  21,  15],
        [ 22,  24,  26]],

       [[ 24,  74, 108],
        [ 22,  27,  30],
        [ 29, 102,  34]]])

In [15]:
np.subtract(a,b)
type(np.subtract)

numpy.ufunc

In [ ]:
np.ufunc()